language: ruby
sudo: false
cache: bundler
bundler_args: --without guard
script: "bundle exec rspec"
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
env:
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.0"
